// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('R3-update-successfully', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('R3-update-successfully', async function() {
    await driver.get("http://localhost:8085/")
    await driver.manage().window().setRect(697, 728)
    await driver.findElement(By.id("login-email")).click()
    await driver.findElement(By.id("login-email")).sendKeys("admin@gmail.com")
    await driver.findElement(By.id("login-password")).click()
    {
      const element = await driver.findElement(By.css(".v-btn__content"))
    }
    await driver.findElement(By.id("login-password")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.findElement(By.id("dash4")).click()
    await driver.executeScript("window.scrollTo(0,229)")
    await driver.findElement(By.css("tr:nth-child(1) .mdi-pencil")).click()
    await driver.findElement(By.id("company-name")).click()
    await driver.findElement(By.id("company-name")).sendKeys("Buhocenter New")
    await driver.findElement(By.id("manager-name")).click()
    await driver.findElement(By.id("manager-name")).click()
    {
      const element = await driver.findElement(By.id("manager-name"))
    }
    await driver.findElement(By.id("manager-name")).sendKeys("Mike")
    await driver.findElement(By.css(".blue--text > .v-btn__content")).click()
  })
})
