// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1.1', function() {
  this.timeout(50000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1.1', async function() {
    await driver.get("http://localhost:8085/")
    await driver.manage().window().setRect(822, 539)
    await driver.findElement(By.id("login-email")).click()
    await driver.findElement(By.id("login-email")).sendKeys("admin@gmail.com")
    await driver.findElement(By.id("login-password")).click()
    {
      const element = await driver.findElement(By.css(".v-btn__content"))
     // await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("login-password")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()
    await driver.wait(until.elementLocated(By.id("dash4")),30000);
    await driver.findElement(By.id("dash4")).click()
    await driver.findElement(By.css(".mdi-plus")).click()
    await driver.findElement(By.css("#AllyForm > .row:nth-child(1)")).click()
    await driver.findElement(By.id("company-name")).click()
    await driver.findElement(By.id("company-name")).sendKeys("gfdfhfd")
    await driver.findElement(By.id("compnay-email")).click()
    await driver.findElement(By.id("compnay-email")).sendKeys("gdggdfg@gmail.com")
    await driver.findElement(By.id("company-phone-number")).click()
    await driver.findElement(By.id("company-phone-number")).sendKeys("+1 (255) 322-2222")
    await driver.findElement(By.id("commercial-ally-description")).click()
    await driver.findElement(By.id("commercial-ally-description")).sendKeys("ghsdgkd")
    await driver.findElement(By.id("manager-name")).click()
    await driver.findElement(By.id("manager-name")).sendKeys("caro")
    await driver.findElement(By.id("manager-last-name")).sendKeys("patino")
    {
      const element = await driver.findElement(By.css(".blue--text > .v-btn__content"))
     // await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".blue--text > .v-btn__content")).click()
  })
})
