// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1.1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1.1', async function() {
    await driver.get("http://localhost:8085/")
    await driver.manage().window().setRect(824, 542)
    await driver.findElement(By.id("login-email")).click()
    await driver.findElement(By.id("login-email")).sendKeys("admin@gmail.com")
    await driver.findElement(By.id("login-password")).click()
    {
      const element = await driver.findElement(By.css(".v-btn__content"))
      //await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("login-password")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()
    await driver.wait(until.elementLocated(By.id("dash4")),30000);
    await driver.findElement(By.id("dash4")).click()
    {
      const element = await driver.findElement(By.css(".mdi-plus"))
      //await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".mdi-plus")).click()
    {
      await driver.wait(until.elementLocated(By.CSS_SELECTOR(),30000);
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      //await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("company-name")).click()
    await driver.wait(until.elementLocated(By.id("company-name")),30000);
    await driver.findElement(By.id("company-name")).sendKeys("galac")
    await driver.findElement(By.id("compnay-email")).click()
    await driver.findElement(By.id("compnay-email")).sendKeys("galac@gmail.com")
    await driver.findElement(By.id("company-phone-number")).click()
    await driver.findElement(By.id("company-phone-number")).sendKeys("+1 (565) 656-5656")
    await driver.findElement(By.id("manager-name")).click()
    await driver.findElement(By.id("manager-name")).sendKeys("Caro")
    await driver.findElement(By.id("manager-last-name")).sendKeys("Patino")
    await driver.findElement(By.id("commercial-ally-description")).click()
    await driver.findElement(By.id("commercial-ally-description")).click()
    await driver.findElement(By.id("commercial-ally-description")).click()
    await driver.findElement(By.id("commercial-ally-description")).sendKeys("hola")
    await driver.findElement(By.css(".blue--text > .v-btn__content")).click()
    {
      const element = await driver.findElement(By.css(".blue--text > .v-btn__content"))
      //await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      //await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
