// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { async } = require('rxjs/internal/scheduler/async')

describe('RUTA2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RUTA2', async function() {
    await driver.get("http://localhost:8085/")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.id("login-email")).click()
    await driver.findElement(By.id("login-email")).sendKeys("admin@gmail.com")
    {
      const element = await driver.findElement(By.css(".v-btn__content"))
     // await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("login-password")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      //await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // setTimeout(()=> {
    //   async function funcy(){
    //     await driver.findElement(By.css(".v-list-item:nth-child(5) > .section-space")).click()
    //   }
    //   funcy();
    // },5000);
    setTimeout(()=> {
      async function funcy(){
        await driver.findElement(By.linkText("Allies")).click()
      }
      funcy();
    },5000);
  })
})
