// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('R6-no-name-provided', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('R6-no-name-provided', async function() {
    await driver.get("http://localhost:8085/")
    await driver.manage().window().setRect(697, 728)
    await driver.findElement(By.id("login-email")).click()
    await driver.findElement(By.id("login-email")).sendKeys("admin@gmail.com")
    await driver.findElement(By.id("login-password")).click()
    {
      const element = await driver.findElement(By.css(".v-btn__content"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("login-password")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.findElement(By.id("dash4")).click()
    await driver.findElement(By.css("tr:nth-child(1) .mdi-magnify")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(1) .mdi-magnify"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("CreateAllieIcon")).click()
    await driver.findElement(By.id("input-196")).click()
    await driver.findElement(By.id("input-196")).sendKeys("New York")
    await driver.findElement(By.id("input-199")).click()
    await driver.findElement(By.id("input-199")).sendKeys("NY")
    await driver.findElement(By.id("input-202")).click()
    await driver.findElement(By.id("input-202")).sendKeys("40, West Brighton Avenue, Brighton Beach, New York, Kings County, New York, 11224, USA")
    await driver.findElement(By.id("input-205")).click()
    await driver.findElement(By.id("input-205")).sendKeys("11224")
    await driver.findElement(By.css(".blue--text > .v-btn__content")).click()
  })
})
